---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2
    apt: 
      name: tree 
      state: present

  - name: i want to restart
    service: 
      name: apache2
      state: restart